language: python
python:
  - 2.7
  - 3.2
  - 3.3
  - 3.4

env:
  - DJANGO='django==1.4.*'
  - DJANGO='django==1.5.*'
  - DJANGO='django==1.6.*'
  - DJANGO='django==1.7.*'
  - DJANGO='django==1.8.*'

install:
  - pip install -q $DJANGO

script: python setup.py test

matrix:
  exclude:
    - python: 3.2
      env: DJANGO='django==1.4.*'
    - python: 3.3
      env: DJANGO='django==1.4.*'
    - python: 3.4
      env: DJANGO='django==1.4.*'

notifications:
  email:
    recipients:
      - bjasper@gmail.com
